// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 developer.glb -T 
// Files: developer.glb [1.37MB] > E:\Projects2\my_3d_portfolio\public\models\developer-transformed.glb [195.48KB] (86%)
// Author: Agor_2012 (https://sketchfab.com/Agor_)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/low-poly-man-working-at-a-table-with-a-laptop-be6b2404359c474fb0ed148e1882516e
// Title: Low poly man working at a table with a laptop
// */

// import React from 'react'
// import { useGraph } from '@react-three/fiber'
// import { useGLTF, useAnimations } from '@react-three/drei'
// import { SkeletonUtils } from 'three-stdlib'

// export function Developer(props) {
//   const group = React.useRef()
//   const { scene, animations } = useGLTF('/models/developer-transformed.glb')
//   const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
//   const { nodes, materials } = useGraph(clone)
//   const { actions } = useAnimations(animations, group)
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group name="Sketchfab_Scene">
//         <group name="GLTF_SceneRootNode">
//           <group name="Empty_1" position={[0.004, 3.004, -0.088]}>
//             <group name="chair_0" position={[-0.041, -0.885, 0.123]} scale={0.754}>
//               <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.PaletteMaterial001} />
//             </group>
//           </group>
//         </group>
//         <primitive object={nodes.GLTF_created_0_rootJoint} />
//         <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.PaletteMaterial001} position={[-3.464, 4.562, 2.562]} rotation={[0, -0.177, 0]} scale={0.755} />
//         <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.material_0} position={[0.13, 4.371, 4.188]} rotation={[1.871, 0, Math.PI]} scale={[0.173, 0.176, 0.177]} />
//         <skinnedMesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_116.skeleton} />
//         <skinnedMesh name="Object_117" geometry={nodes.Object_117.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_117.skeleton} />
//         <skinnedMesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_118.skeleton} />
//         <skinnedMesh name="Object_119" geometry={nodes.Object_119.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_119.skeleton} />
//         <skinnedMesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.PaletteMaterial001} skeleton={nodes.Object_120.skeleton} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/models/developer-transformed.glb')


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 developer.glb -T 
Author: Agor_2012 (https://sketchfab.com/Agor_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Title: Low poly man working at a table with a laptop
*/

import React, { useEffect, useMemo, useRef } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Developer(props) {
  const group = useRef();
  const { scene, animations } = useGLTF("/models/developer-transformed.glb");

  // Clone the scene so animations work correctly with multiple instances
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    // Play all available actions (usually there is only one)
    if (actions) {
      Object.values(actions).forEach((action) => {
        if (action) {
          action.reset().play();
        }
      });
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Empty_1" position={[0.004, 3.004, -0.088]}>
            <group
              name="chair_0"
              position={[-0.041, -0.885, 0.123]}
              scale={0.754}
            >
              <mesh
                name="Object_5"
                geometry={nodes.Object_5.geometry}
                material={materials.PaletteMaterial001}
              />
            </group>
          </group>
        </group>

        {/* Skeleton root */}
        <primitive object={nodes.GLTF_created_0_rootJoint} />

        {/* Table / laptop etc */}
        <mesh
          name="Object_10"
          geometry={nodes.Object_10.geometry}
          material={materials.PaletteMaterial001}
          position={[-3.464, 4.562, 2.562]}
          rotation={[0, -0.177, 0]}
          scale={0.755}
          castShadow
          receiveShadow
        />
        <mesh
          name="Object_21"
          geometry={nodes.Object_21.geometry}
          material={materials.material_0}
          position={[0.13, 4.371, 4.188]}
          rotation={[1.871, 0, Math.PI]}
          scale={[0.173, 0.176, 0.177]}
          castShadow
          receiveShadow
        />

        {/* Character skinned meshes */}
        <skinnedMesh
          name="Object_116"
          geometry={nodes.Object_116.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_116.skeleton}
        />
        <skinnedMesh
          name="Object_117"
          geometry={nodes.Object_117.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_117.skeleton}
        />
        <skinnedMesh
          name="Object_118"
          geometry={nodes.Object_118.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_118.skeleton}
        />
        <skinnedMesh
          name="Object_119"
          geometry={nodes.Object_119.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_119.skeleton}
        />
        <skinnedMesh
          name="Object_120"
          geometry={nodes.Object_120.geometry}
          material={materials.PaletteMaterial001}
          skeleton={nodes.Object_120.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/developer-transformed.glb");

